export { classifyNormalForm } from "./classifyNormalForm"
export type { NormalFormVerdict, NormalFormViolation } from "./classifyNormalForm"
export { createCanonicalizer, normalizeByStage, normalizeTo3NF } from "./normalizeTo3NF"
export type { NormalizationStages } from "./normalizeTo3NF"
export { generateDdl } from "./generateDdl"
export { projectTableRows } from "./projectTableRows"
export { toErDiagram } from "./toErDiagram"
