/**
 * Safely quotes an arbitrary SQL identifier (schema, table, or column name)
 * for interpolation into DDL/DML where a bind parameter is impossible.
 *
 * Wrapping in double quotes and doubling any embedded double quote is
 * Postgres's own escaping rule for a quoted identifier. It is sufficient on
 * its own to prevent injection through the identifier position: once
 * wrapped, the only character that can end the identifier early is an
 * unescaped `"`, and every `"` in the input is escaped before quoting.
 *
 * Used for table names discovered via `information_schema`, which are
 * chosen by the uploaded script's author and can legitimately contain
 * characters an allowlist would reject (spaces, unicode, mixed case).
 * Schema names, in contrast, are generated by this application and are
 * additionally restricted by `parseStagingSchemaName`'s allowlist — see
 * that module for why quoting alone is not enough there.
 */
export function quoteIdentifier(identifier: string): string {
  return `"${identifier.replaceAll('"', '""')}"`
}
