import { err, ok, type Result } from "./result"
import { quoteIdentifier } from "./sqlIdentifier"

/**
 * A validated staging schema name.
 *
 * Constructed only by `parseStagingSchemaName`. The schema name is
 * interpolated into DDL (`CREATE SCHEMA`, `SET search_path`, `DROP SCHEMA`)
 * where a bind parameter is impossible, so quoting via `quoteIdentifier`
 * alone is not the whole story: this type is also generated by our own
 * application code (never taken verbatim from the uploaded script), so an
 * allowlist can be applied without breaking any legitimate use case. That
 * gives us two independent layers — allowlist, then quoting — against a
 * mistake in either one.
 */
export type StagingSchemaName = string & { readonly __brand: "StagingSchemaName" }

export type InvalidStagingSchemaNameError = {
  readonly kind: "invalid-staging-schema-name"
  readonly reason: "empty" | "too-long" | "disallowed-characters"
}

// Lowercase ASCII letters, digits, and underscores only, starting with a
// letter or underscore. This mirrors Postgres's own unquoted-identifier
// grammar and rejects everything an injection attempt would need (quotes,
// semicolons, whitespace, non-ASCII lookalikes).
const STAGING_SCHEMA_NAME_PATTERN = /^[a-z_][a-z0-9_]*$/

// Postgres truncates identifiers over 63 bytes (NAMEDATALEN - 1); reject
// anything that would silently collide with another truncated name instead
// of letting the database decide.
const MAX_STAGING_SCHEMA_NAME_LENGTH = 63

export function parseStagingSchemaName(
  candidate: string,
): Result<StagingSchemaName, InvalidStagingSchemaNameError> {
  if (candidate.length === 0) {
    return err({ kind: "invalid-staging-schema-name", reason: "empty" })
  }
  if (candidate.length > MAX_STAGING_SCHEMA_NAME_LENGTH) {
    return err({ kind: "invalid-staging-schema-name", reason: "too-long" })
  }
  if (!STAGING_SCHEMA_NAME_PATTERN.test(candidate)) {
    return err({ kind: "invalid-staging-schema-name", reason: "disallowed-characters" })
  }
  return ok(candidate as StagingSchemaName)
}

/** Quotes a validated schema name for interpolation into DDL. */
export function quoteStagingSchemaName(schema: StagingSchemaName): string {
  return quoteIdentifier(schema)
}
